version: "3.7"
services:
  s3:
    image: minio/minio:latest
    ports:
      - 9876:9000
    environment:
      - MINIO_ACCESS_KEY=${AWS_ACCESS_KEY_ID}
      - MINIO_SECRET_KEY=${AWS_SECRET_ACCESS_KEY}
    command: 
      server /data
    networks:
      - traefik-public
    volumes:
      - s3-data:/data
    deploy:
        placement:
          constraints: [node.role == manager]
        labels:
          - traefik.enable=true
          - traefik.docker.network=traefik-public
          - traefik.constraint-label=traefik-public
          - traefik.http.routers.${STACK_NAME?Variable not set}-s3-http.rule=Host(`s3.${DOMAIN?Variable not set}`)
          - traefik.http.routers.${STACK_NAME?Variable not set}-s3-http.entrypoints=http
          - traefik.http.routers.${STACK_NAME?Variable not set}-s3-http.middlewares=https-redirect
          - traefik.http.routers.${STACK_NAME?Variable not set}-s3-https.rule=Host(`s3.${DOMAIN?Variable not set}`)
          - traefik.http.routers.${STACK_NAME?Variable not set}-s3-https.entrypoints=https
          - traefik.http.routers.${STACK_NAME?Variable not set}-s3-https.tls=true
          - traefik.http.routers.${STACK_NAME?Variable not set}-s3-https.tls.certresolver=le
          - traefik.http.services.${STACK_NAME?Variable not set}-s3.loadbalancer.server.port=9000

volumes:
  s3-data:

networks:
  traefik-public:
    external: true