version: '3.2'

services:
  agent:
    image: portainer/agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  portainer:
    image: portainer/portainer-ce
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    ports:
      - "9000:9000"
      - "8000:8000"
    volumes:
      - portainer_data:/data
    networks:
      - agent_network
      - traefik-public
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.${STACK_NAME?Variable not set}-portainer-http.rule=Host(`portainer.${DOMAIN?Variable not set}`)
        - traefik.http.routers.${STACK_NAME?Variable not set}-portainer-http.entrypoints=http
        - traefik.http.routers.${STACK_NAME?Variable not set}-portainer-http.middlewares=https-redirect
        - traefik.http.routers.${STACK_NAME?Variable not set}-portainer-https.rule=Host(`portainer.${DOMAIN?Variable not set}`)
        - traefik.http.routers.${STACK_NAME?Variable not set}-portainer-https.entrypoints=https
        - traefik.http.routers.${STACK_NAME?Variable not set}-portainer-https.tls=true
        - traefik.http.routers.${STACK_NAME?Variable not set}-portainer-https.tls.certresolver=le
        - traefik.http.services.${STACK_NAME?Variable not set}-portainer.loadbalancer.server.port=9000

networks:
  agent_network:
    driver: overlay
    attachable: true
  traefik-public:
    external: true

volumes:
  portainer_data:
